### ISSUE TITLE
[BUG] [Quilt 1.19.2] Server will not start

### ISSUE THREAD

**Issue by JLUsr** [squeeglii/grapplemod#1]
**Describe the bug**
Crash on launch

**Version**
Include the versions for:
- The Grapple Hook Mod
[v1](https://modrinth.com/mod/grappling-hook-mod-fabric/version/1.19.2-v1)
- The Mod Loader (/ - include the api mod's version)
Quilt 0.17.11 | [QFAPI 4.0.0-beta.27 and QSL 3.0.0-beta.29](https://modrinth.com/mod/qsl/version/4.0.0-beta.27%2B0.73.0-1.19.2) (Provides Fabric API 0.73.0)
- Minecraft
1.19.2

**Output Log**
See this [gist](https://gist.github.com/JLUsr/17ed8526fc7307f451b9fd0cba8a5f23).

**To Reproduce**
If you can, steps to reproduce the behavior, e.g.:
1. Install mod on the server
2. Start the server
3. See console output error

**Comment by squeeglii** [comment]
Fixed as of [51c2366](https://github.com/CloudG360/grapplemod-restitched/commit/51c2366c8d4c3a205e2ded7d57e83757f4b7e5ac) but the fix has revealed new issues.

**Comment by squeeglii** [comment]
Working patch as of [d830bd3](https://github.com/CloudG360/grapplemod-restitched/commit/d830bd37ff0cc70a378cc8abfff717c5b9d15dcc) for 1.19.2! - Will be updated in a few hours on Curse/Modrinth
