### ISSUE TITLE
[BUG] Whenever I press F5 it shows my front view first, then my back view

### ISSUE THREAD

**Issue by DomDumm** [squeeglii/grapplemod#10]
[empty]

**Comment by squeeglii** [comment]
Recreated with the base mod - will investigate

**Comment by squeeglii** [comment]
Fixed as of [9376ddf](https://github.com/CloudG360/grapplemod-restitched/commit/9376ddf3be7ef0d105676ac82818eee949a6ea52) - Will be in a hotfix real soon!
