### ISSUE TITLE
[INCOMPATIBILITY] Aileron & Amethyst Gravity

### ISSUE THREAD

**Issue by JLUsr** [squeeglii/grapplemod#3]
**Describe the bug**
Random disconnect from server (sometimes crash) when Aileron & Amethyst Gravity are installed and the player has connected the Grapple Hook to a block.

**Version**
Include the versions for:
 - The Grapple Hook Mod
 v1.1
 - The Mod Loader (/ - include the api mod's version)
 Quilt 0.17.11 | [QFAPI 4.0.0-beta.27 and QSL 3.0.0-beta.29](https://modrinth.com/mod/qsl/version/4.0.0-beta.27%2B0.73.0-1.19.2) (Provides Fabric API 0.73.0)
 - Minecraft
 1.19.2
 - Any potentially affected mods
[Aileron 1.19 Fabric v1.0.0](https://modrinth.com/mod/aileron/version/1.0.0-1.19-fabric) (Yes, the Fabric version. I recently started using quilt and have not fully changed each Fabric mod to its Quilt alternative at this point)
[Amethyst Gravity 1.19.2 Quilt v1.1.1](https://modrinth.com/mod/amethyst-gravity/version/1.1.1)

**Output Log**
[Gist](https://gist.github.com/JLUsr/3296aa7af15fa1df738c2cf51092a266)

**Steps To Reproduce**
If you can, steps to reproduce the behavior, e.g.:
1. Start a server with Grapplemod-Restitched and the other affected mods installed
2. Connect and use the Grapple Hook a few times (swing around a bit, constantly unhook and rehook to blocks a few times)
3. Possibly disconnect at this point(?)
4. See server console for detailed output error

**Additional context**
This issue occured with a large mod list initially and took some time for me to work through. The Gist I provided goes over...
1. Running a server with both Aileron and Amethyst Gravity installed. Running the two mods together increases the probability of getting disconnected with an error of `Index -1 out of bounds for length 10`; however, this error stems from Amethyst Gravity rather than Aileron. I was able to recreate this with just Amethyst Gravity; however, it took an long time for the issue to actually occur.
2. Running a server without Amethyst Gravity. Rather than the player getting kicked/disconnected this causes the server to restart, but did not generate a crash-report
3. The third log is the initial error I had (both Aileron and Amethyst Gravity are present) in which the player was disconnected whilst using the Grapple Hook. Many other mods were installed at this time, hence why it is at the bottom of the list. I only included it since the information is similar to the scenario in which I reproduced the issue with just Aileron and Amethyst Gravity with a little extra info at the end.

**Comment by squeeglii** [comment]
Unable to reproduce but this is after the fixes of [79b1933](https://github.com/CloudG360/grapplemod-restitched/commit/79b1933fa1c5c9591d33961b2cfb39ab6feb7074) which affected a part that could've had a knock-on effect.

Please try again with v1.2 when that gets approved 😅 - I'll leave the issue open for a week just in case it's not actually fixed.

**Comment by JLUsr** [comment]
Unable to reproduce the issue with v1.2! This has indeed been fixed.
