### ISSUE TITLE
[BUG] Crash when crafting rocket grapple item

### ISSUE THREAD

**Issue by netcore10** [squeeglii/grapplemod#5]
**Describe the bug**
when you try to craft it, i crashed

**Video / Screenshots**

**Version**
Include the versions for:
- The Grapple Hook Mod 
- The Mod Loader (fabric/quilt - include the api mod's version)  quilt loader 18.1 - beta 73, qfapi 4.0 beta 27
- Minecraft - 1.19.2

**Output Log**

[https://paste.atlauncher.com/view/7c89e6c4-430b-4737-93bc-d6b28dae6ef4
](https://paste.atlauncher.com/view/7c89e6c4-430b-4737-93bc-d6b28dae6ef4)

**To Reproduce**
If you can, steps to reproduce the behavior, e.g.:
1. craft rocket grapple, try to put in inventory
2. crash
**Additional context**

**Comment by netcore10** [comment]
Forgot to supply this, sorry. 
[crash-2023-02-08_20.35.12-client.txt](https://github.com/CloudG360/grapplemod-restitched/files/10700068/crash-2023-02-08_20.35.12-client.txt)

**Comment by squeeglii** [comment]
The recipes are being removed in the next update as they're broken in 1.19.3. Should have a replacement soon. If you want to customize them using the Grapple Modifier Block in the meantime, here are the properties to use:

- Rope > Rope Length = 60
- Hook Thrower > Throw Speed = 3.5
- Rocket > Rocket = On

Possibly a mod incompatibility? Looking into it.

**Comment by squeeglii** [comment]
Issue fixed as of [dfcd48b](https://github.com/CloudG360/grapplemod-restitched/commit/dfcd48b89b2a5adaab8ed3cd23f4ed6314d64ae7)
