### ISSUE TITLE
Rocket Grapple Crash

### ISSUE THREAD

**Issue by shigzn** [squeeglii/grapplemod#7]
Whenever I right-click with the Rocket Configuration on the Grapple, it immediately crashes the game.
Using Fabric 1.18.2

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2/12/23, 3:47 AM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.class_287.method_22632(class_287.java:371)
	at net.minecraft.class_286.method_1309(class_286.java:50)
	at net.minecraft.class_329.drawRect(class_329.java:4613)
	at net.minecraft.class_329.handler$bho000$renderModCrosshair(class_329.java:4588)
	at net.minecraft.class_329.method_1736(class_329.java:457)
	at net.minecraft.class_329.method_1753(class_329.java:235)
	at net.minecraft.class_757.method_3192(class_757.java:858)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.class_287.method_22632(class_287.java:371)
	at net.minecraft.class_286.method_1309(class_286.java:50)
	at net.minecraft.class_329.drawRect(class_329.java:4613)
	at net.minecraft.class_329.handler$bho000$renderModCrosshair(class_329.java:4588)
	at net.minecraft.class_329.method_1736(class_329.java:457)
	at net.minecraft.class_329.method_1753(class_329.java:235)

-- Affected level --
Details:
	All players: 1 total; [class_746['shigzn'/60, l='ClientLevel', x=314.32, y=52.00, z=195.81]]
	Chunk stats: 4096, 1110
	Level dimension: minecraft:overworld
	Level spawn location: World: (254,64,-43), Section: (at 14,0,5 in 15,4,-3; chunk contains blocks 240,-64,-48 to 255,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 1320310 game time, 626545 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, beta_foliage.zip, 1.18.2 Solon't, minecraft/physicsmod

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 723348648 bytes (689 MiB) / 2694840320 bytes (2570 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3800X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.89
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f08
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2802
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37555.68
	Virtual memory used (MB): 24189.94
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 221.13
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		ad_astra: Ad Astra 1.0.6
			team_reborn_energy: Energy 2.2.0
		advancedcombat: Advanced Combat (Revitalized) 1.0-SNAPSHOT
		appleskin: AppleSkin 2.4.1+mc1.18.2
		architectury: Architectury 4.11.89
		bucolicorigins: Bucolic_Origins[FABRIC] 3.5
		cardinal-components: Cardinal Components API 4.2.0
			cardinal-components-base: Cardinal Components API (base) 4.2.0
			cardinal-components-block: Cardinal Components API (blocks) 4.2.0
			cardinal-components-chunk: Cardinal Components API (chunks) 4.2.0
			cardinal-components-entity: Cardinal Components API (entities) 4.2.0
			cardinal-components-item: Cardinal Components API (items) 4.2.0
			cardinal-components-level: Cardinal Components API (world saves) 4.2.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.2.0
			cardinal-components-world: Cardinal Components API (worlds) 4.2.0
		castle_dungeons: Castle Dungeons 3.3-1.18.2-fabric
		chisel: Chisel Refabricated 1.4.5
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 2.0.1+1.18.2
		couplings: Couplings 1.8.0+1.18.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		crawl: Crawl 0.10.6
			mm: Manningham Mills 2.3
		customportals: Custom Portals 3.0.1
			completeconfig: CompleteConfig 1.3.3
		damagetilt: Damage Tilt 1.18-fabric-0.1.2
		darkness: True Darkness 2.0.91
		extradiscs: Extra Discs 1.0.1
		fabric-api: Fabric API 0.67.1+1.18.2
			fabric-api-base: Fabric API Base 0.4.5+64b7c69360
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.13+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.2+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.2+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.3+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.21+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+a6f01b2660
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.15+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.5+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.7+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.4+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.16+ee3621fc60
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.6+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.12+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.14+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.8+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.11+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.13+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.14
		fallingtree: FallingTree 3.5.4
		forgeconfigapiport: Forge Config API Port 3.2.4
		gateofbabylon: Gate Of Babylon 1.7.0-1.18.2
		grapplemod: Grappling Hook Mod 1.18.2-v1.3
		grindenchantments: Grind Enchantments 1.6.4+1.18.2
		hookshot: Hookshot 25.0
		horseinboat: HorseInBoat 1.1.2
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		hunger_remover: Hunger Remover 1.0.3
		immersive_aircraft: Immersive Aircraft 0.3.0+1.18.2
		indium: Indium 1.0.7+mc1.18.2
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.10.3
		mcwbridges: Macaw's Bridges 1.0.6
		mcwdoors: Macaw's Doors 1.0.8
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwwindows: Macaw's Windows 2.1.2
		minecarttweaks: Cammie's Minecart Tweaks 1.5
		minecraft: Minecraft 1.18.2
		mocolors: Mo' Colors 1.4.0
			libgui: LibGui 5.3.1+1.18
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		modern_beta: Modern Beta Fabric 4.0.2+1.18.2
		modmenu: Mod Menu 3.2.5
		morediscs: More discs 1.18.2-25
		mousetweaks: Mouse Tweaks 2.22
		nostalgic_tweaks: Nostalgic Tweaks 1.0.7
		notenoughanimations: NotEnoughAnimations 1.6.0
		old_combat_mod: Old Combat Mod 1.1
		oldwalkinganimation: Old Walking Animation 1.1.0
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
				calio: Calio 1.5.1
				playerabilitylib: Pal 1.5.0
		origins-classes: Origins: Classes 1.3.0
		owo: oωo 0.7.2-no-cme+1.18
		patchouli: Patchouli 1.18.2-71.1-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.6.3+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		physicsmod: Physics Mod 2.9.5
		portalcubed: Portal Cubed 2.1.8
			gravitychanger: GravityChanger 0.7.1
			stonecutter_recipe_tags: Stonecutter Recipe Tags 3.0.1+1.18.bc850d5.fabric
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.18.2-build.66
		reinfchest: Reinforced Chests 2.2.0+1.18
			reinfcore: Reinforced Core 3.0.3+1.18
		roughlyenoughitems: Roughly Enough Items 8.3.588
			error_notifier: Error Notifier 1.0.9
		scooters: Scooters 1.0.1
		silkspawners: SilkSpawners 1.1.1
		skinlayers: 3d Skin Layers 1.5.2-mc1.18.2
		smallships: Small Ships 2.0.0a1.1.1
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.17+mc1.18.2-build.94
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.6
		sound_track: Sound-Track 1.0.7
		spyglass-improvements: Spyglass Improvements 1.2+mc1.18.2+fabric
		sulfurpotassiummod: Sulfur & Potassium 1.1.2
		the_aether: Paradise Lost 1.6.9+1.18.2
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
			customportalapi: Custom Portal Api 0.0.1-beta50-1.18
			gud_recipe_confidence: Recipe Confidence 1.0.2
			incubus_core: Incubus Core 1.6.6+1.18.2
			moretags: More Tags 3.0.4
			satin: Satin 1.7.2
		things: Things 0.2.18+1.18
		transportables: Transportables 1.2
		travelersbackpack: Traveler's Backpack 1.18.2-7.1.18
			reach-entity-attributes: Reach Entity Attributes 2.2.0
		trinkets: Trinkets 3.3.1
		zihlaunchpads: ZIHLaunchpads 1.2.0
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.14-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.02, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/beta_foliage.zip (incompatible), file/1.18.2 Solon't, minecraft/physicsmod
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3800X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['shigzn'/60, l='ServerLevel[Modern Beta (Normal Biomes)]', x=314.32, y=52.00, z=195.81]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental

**Comment by squeeglii** [comment]
Reproduced successfully using the base mod - investigating :)

**Comment by squeeglii** [comment]
Fixed as of [546e345](https://github.com/CloudG360/grapplemod-restitched/commit/546e3459237442072825a71ddc664e1e2bd939a5) - Will be published immediately with 1.18.2-v1.3b :)

**Comment by shigzn** [comment]
👍
