### ISSUE TITLE
cant swap item to offhand with hotkey

### ISSUE THREAD

**Issue by LeonardNid** [squeeglii/grapplemod#8]
**Describe the bug**
I cant swap any item in my offhand or out of my offhand with the hotkey "f". Testet it with other hotkeys and still doesn't work.

**Version**
Include the versions for:
- The Grapple Hook Mod : grapplemod-1.18.2-v1.3b.jar
- The Mod Loader (fabric/quilt - include the api mod's version) : fabric-api-0.67.1+1.18.2.jar
- Minecraft 1.18.2

**Output Log**
An example log when the problem occurred. (Getting the log with the default Minecraft launcher: https://instant-structures-mod.com/tutorials/game-output-log/)
<details>
example log
</details>

**To Reproduce**
If you can, steps to reproduce the behavior, e.g.:
pick an item and press "f" or the hotkey assigned to "swap to offhand"

**Additional context**
i tested it with just the mod and no other mods and still doesn't work
i also tried 1.19.3 and there it also didn't work

**Comment by squeeglii** [comment]
Reproduced it successfully - Investigating! :)

**Comment by squeeglii** [comment]
Linked to issue #10 - Keybinds are being fired twice.

**Comment by squeeglii** [comment]
Fixed as of [9376ddf](https://github.com/CloudG360/grapplemod-restitched/commit/9376ddf3be7ef0d105676ac82818eee949a6ea52) - Will be in a hotfix real soon!
